- name: Ensure system is Debian
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Debian"

- name: Add Adoptium repository (USTC mirror)
  ansible.builtin.deb822_repository:
    name: adoptium
    uris: https://mirrors.ustc.edu.cn/adoptium/deb/
    suites: '{{ ansible_distribution_release }}'
    components: main
    signed_by: https://packages.adoptium.net/artifactory/api/gpg/key/public

- name: Install Temurin JDK
  ansible.builtin.apt:
    name: temurin-{{ temurin_version }}-jdk
    update_cache: true
