- name: Populate service facts
  ansible.builtin.service_facts:

- name: Template Alloy config
  ansible.builtin.template:
    src: minecraft.alloy.j2
    dest: /etc/alloy/minecraft.alloy
    mode: '0644'

- name: Restart Alloy service if present
  ansible.builtin.systemd_service:
    name: alloy
    state: restarted
  when: '"alloy.service" in ansible_facts.services'
